/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCobrancasRouteImport } from './routes/_authenticated/cobrancas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFaturamentoRouteImport } from './routes/_authenticated/faturamento'
import { Route as AuthenticatedMinhaLojaRouteImport } from './routes/_authenticated/minha-loja'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedProdutosIaRouteImport } from './routes/_authenticated/produtos-ia'
import { Route as AuthenticatedQrcodesRouteImport } from './routes/_authenticated/qrcodes'
import { Route as CobrancaTokenRouteImport } from './routes/cobranca.$token'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedAdminFaturamentoRouteImport } from './routes/_authenticated/admin.faturamento'
import { Route as AuthenticatedAdminLandingRouteImport } from './routes/_authenticated/admin.landing'
import { Route as AuthenticatedAdminLojasRouteImport } from './routes/_authenticated/admin.lojas'
import { Route as AuthenticatedAdminPrecosRouteImport } from './routes/_authenticated/admin.precos'
import { Route as AuthenticatedAdminSolicitacoesProRouteImport } from './routes/_authenticated/admin_.solicitacoes-pro'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCobrancasRoute = AuthenticatedCobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturamentoRoute =
  AuthenticatedFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhaLojaRoute = AuthenticatedMinhaLojaRouteImport.update({
  id: '/minha-loja',
  path: '/minha-loja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosIaRoute = AuthenticatedProdutosIaRouteImport.update({
  id: '/produtos-ia',
  path: '/produtos-ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrcodesRoute = AuthenticatedQrcodesRouteImport.update({
  id: '/qrcodes',
  path: '/qrcodes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CobrancaTokenRoute = CobrancaTokenRouteImport.update({
  id: '/cobranca/$token',
  path: '/cobranca/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminFaturamentoRoute =
  AuthenticatedAdminFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLandingRoute =
  AuthenticatedAdminLandingRouteImport.update({
    id: '/landing',
    path: '/landing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLojasRoute = AuthenticatedAdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPrecosRoute =
  AuthenticatedAdminPrecosRouteImport.update({
    id: '/precos',
    path: '/precos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSolicitacoesProRoute =
  AuthenticatedAdminSolicitacoesProRouteImport.update({
    id: '/admin_/solicitacoes-pro',
    path: '/admin/solicitacoes-pro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/minha-loja': typeof AuthenticatedMinhaLojaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/produtos-ia': typeof AuthenticatedProdutosIaRoute
  '/qrcodes': typeof AuthenticatedQrcodesRoute
  '/cobranca/$token': typeof CobrancaTokenRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/admin/faturamento': typeof AuthenticatedAdminFaturamentoRoute
  '/admin/landing': typeof AuthenticatedAdminLandingRoute
  '/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/admin/precos': typeof AuthenticatedAdminPrecosRoute
  '/admin/solicitacoes-pro': typeof AuthenticatedAdminSolicitacoesProRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/minha-loja': typeof AuthenticatedMinhaLojaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/produtos-ia': typeof AuthenticatedProdutosIaRoute
  '/qrcodes': typeof AuthenticatedQrcodesRoute
  '/cobranca/$token': typeof CobrancaTokenRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/admin/faturamento': typeof AuthenticatedAdminFaturamentoRoute
  '/admin/landing': typeof AuthenticatedAdminLandingRoute
  '/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/admin/precos': typeof AuthenticatedAdminPrecosRoute
  '/admin/solicitacoes-pro': typeof AuthenticatedAdminSolicitacoesProRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/cobrancas': typeof AuthenticatedCobrancasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/faturamento': typeof AuthenticatedFaturamentoRoute
  '/_authenticated/minha-loja': typeof AuthenticatedMinhaLojaRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/produtos-ia': typeof AuthenticatedProdutosIaRoute
  '/_authenticated/qrcodes': typeof AuthenticatedQrcodesRoute
  '/cobranca/$token': typeof CobrancaTokenRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/s/$slug': typeof SSlugRoute
  '/_authenticated/admin/faturamento': typeof AuthenticatedAdminFaturamentoRoute
  '/_authenticated/admin/landing': typeof AuthenticatedAdminLandingRoute
  '/_authenticated/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/_authenticated/admin/precos': typeof AuthenticatedAdminPrecosRoute
  '/_authenticated/admin_/solicitacoes-pro': typeof AuthenticatedAdminSolicitacoesProRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recuperar-senha'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/assinatura'
    | '/clientes'
    | '/cobrancas'
    | '/configuracoes'
    | '/dashboard'
    | '/faturamento'
    | '/minha-loja'
    | '/onboarding'
    | '/pedidos'
    | '/produtos'
    | '/produtos-ia'
    | '/qrcodes'
    | '/cobranca/$token'
    | '/loja/$slug'
    | '/s/$slug'
    | '/admin/faturamento'
    | '/admin/landing'
    | '/admin/lojas'
    | '/admin/precos'
    | '/admin/solicitacoes-pro'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recuperar-senha'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/assinatura'
    | '/clientes'
    | '/cobrancas'
    | '/configuracoes'
    | '/dashboard'
    | '/faturamento'
    | '/minha-loja'
    | '/onboarding'
    | '/pedidos'
    | '/produtos'
    | '/produtos-ia'
    | '/qrcodes'
    | '/cobranca/$token'
    | '/loja/$slug'
    | '/s/$slug'
    | '/admin/faturamento'
    | '/admin/landing'
    | '/admin/lojas'
    | '/admin/precos'
    | '/admin/solicitacoes-pro'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/recuperar-senha'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/assinatura'
    | '/_authenticated/clientes'
    | '/_authenticated/cobrancas'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/faturamento'
    | '/_authenticated/minha-loja'
    | '/_authenticated/onboarding'
    | '/_authenticated/pedidos'
    | '/_authenticated/produtos'
    | '/_authenticated/produtos-ia'
    | '/_authenticated/qrcodes'
    | '/cobranca/$token'
    | '/loja/$slug'
    | '/s/$slug'
    | '/_authenticated/admin/faturamento'
    | '/_authenticated/admin/landing'
    | '/_authenticated/admin/lojas'
    | '/_authenticated/admin/precos'
    | '/_authenticated/admin_/solicitacoes-pro'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CobrancaTokenRoute: typeof CobrancaTokenRoute
  LojaSlugRoute: typeof LojaSlugRoute
  SSlugRoute: typeof SSlugRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cobrancas': {
      id: '/_authenticated/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof AuthenticatedCobrancasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturamento': {
      id: '/_authenticated/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof AuthenticatedFaturamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-loja': {
      id: '/_authenticated/minha-loja'
      path: '/minha-loja'
      fullPath: '/minha-loja'
      preLoaderRoute: typeof AuthenticatedMinhaLojaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos-ia': {
      id: '/_authenticated/produtos-ia'
      path: '/produtos-ia'
      fullPath: '/produtos-ia'
      preLoaderRoute: typeof AuthenticatedProdutosIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qrcodes': {
      id: '/_authenticated/qrcodes'
      path: '/qrcodes'
      fullPath: '/qrcodes'
      preLoaderRoute: typeof AuthenticatedQrcodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cobranca/$token': {
      id: '/cobranca/$token'
      path: '/cobranca/$token'
      fullPath: '/cobranca/$token'
      preLoaderRoute: typeof CobrancaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/faturamento': {
      id: '/_authenticated/admin/faturamento'
      path: '/faturamento'
      fullPath: '/admin/faturamento'
      preLoaderRoute: typeof AuthenticatedAdminFaturamentoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/landing': {
      id: '/_authenticated/admin/landing'
      path: '/landing'
      fullPath: '/admin/landing'
      preLoaderRoute: typeof AuthenticatedAdminLandingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lojas': {
      id: '/_authenticated/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AuthenticatedAdminLojasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/precos': {
      id: '/_authenticated/admin/precos'
      path: '/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AuthenticatedAdminPrecosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin_/solicitacoes-pro': {
      id: '/_authenticated/admin_/solicitacoes-pro'
      path: '/admin/solicitacoes-pro'
      fullPath: '/admin/solicitacoes-pro'
      preLoaderRoute: typeof AuthenticatedAdminSolicitacoesProRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminFaturamentoRoute: typeof AuthenticatedAdminFaturamentoRoute
  AuthenticatedAdminLandingRoute: typeof AuthenticatedAdminLandingRoute
  AuthenticatedAdminLojasRoute: typeof AuthenticatedAdminLojasRoute
  AuthenticatedAdminPrecosRoute: typeof AuthenticatedAdminPrecosRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminFaturamentoRoute: AuthenticatedAdminFaturamentoRoute,
  AuthenticatedAdminLandingRoute: AuthenticatedAdminLandingRoute,
  AuthenticatedAdminLojasRoute: AuthenticatedAdminLojasRoute,
  AuthenticatedAdminPrecosRoute: AuthenticatedAdminPrecosRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCobrancasRoute: typeof AuthenticatedCobrancasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFaturamentoRoute: typeof AuthenticatedFaturamentoRoute
  AuthenticatedMinhaLojaRoute: typeof AuthenticatedMinhaLojaRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedProdutosIaRoute: typeof AuthenticatedProdutosIaRoute
  AuthenticatedQrcodesRoute: typeof AuthenticatedQrcodesRoute
  AuthenticatedAdminSolicitacoesProRoute: typeof AuthenticatedAdminSolicitacoesProRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCobrancasRoute: AuthenticatedCobrancasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFaturamentoRoute: AuthenticatedFaturamentoRoute,
  AuthenticatedMinhaLojaRoute: AuthenticatedMinhaLojaRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedProdutosIaRoute: AuthenticatedProdutosIaRoute,
  AuthenticatedQrcodesRoute: AuthenticatedQrcodesRoute,
  AuthenticatedAdminSolicitacoesProRoute:
    AuthenticatedAdminSolicitacoesProRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CobrancaTokenRoute: CobrancaTokenRoute,
  LojaSlugRoute: LojaSlugRoute,
  SSlugRoute: SSlugRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
